//! AUTO-GENERATED — DO NOT EDIT BY HAND.
//!
//! coord-tui's daemon **write** client (#2900, Phase 4 of code-coordinator#2894),
//! generated by `scripts/codegen.py --rust` alongside its read-path sibling
//! `generated.rs`. Both come from `coord.serve_app.openapi_spec()`; this file
//! covers the `requestBody` / `200` response of every route coord-tui POSTs
//! or PATCHes. Regenerate after any wire change:
//!
//! ```text
//! COORD_TUI_SRC=<coord-tui checkout root> .venv/bin/python scripts/codegen.py --rust
//! ```
//!
//! (`text` is load-bearing: rustdoc compiles an unannotated code block in a
//! doc comment as a doctest.)
//!
//! **Why this file exists.** Before #2900 these bodies were hand-built
//! `serde_json::json!({...})` literals. Inside one repo that was a tolerable
//! mirror — one PR changed both sides and one CI run saw it. Since #2899 put
//! coord-tui in its own repo it is a cross-repo contract per endpoint, each
//! free to drift in silence; and unlike a drifted READ (which blanks a panel
//! loudly) a drifted WRITE silently records the wrong thing.
//!
//! **`X-Coord-Schema` (#1943).** Each request type carries a `SCHEMA_HEADER`
//! const: `Some(v)` on the resource-shaped routes (`/issue/{repo}/{n}`),
//! `None` on the verb routes, whose handlers read an absent header as
//! "today's shape". Send the header when, and only when, it is `Some` — that
//! asymmetry is what lets coord-tui migrate one endpoint at a time on its own
//! deploy lane, with a client-side one-liner as the rollback
//! (docs/STORE_SERVICE.md §4).
//!
//! **Absent is not null on a PATCH.** Fields of a partial-update route are
//! `Option<Option<T>>`: `None` omits the key (leave alone), `Some(None)`
//! sends an explicit `null` (clear), `Some(Some(v))` sets. Fields of a verb
//! route are a plain `Option<T>` and serialize their `None` as an explicit
//! `null`, byte-identical to the literal each one replaces.
//!
//! Every response field is `#[serde(default)]` for the same reason every
//! `/board` field is: one unexpected key must not turn a successful write
//! into a displayed parse error.

/// A nested request DTO — `coord.rest_schema.IssueUpsertIssue` (#2900).
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct IssueUpsertIssue {
    pub(crate) number: i64,
    pub(crate) title: Option<String>,
    pub(crate) body: Option<String>,
    pub(crate) state: Option<String>,
    pub(crate) labels: Option<Vec<String>>,
    pub(crate) milestone_number: Option<i64>,
    pub(crate) milestone_title: Option<String>,
}

/// `POST /test-verdict` — Record a Test-gate verdict (#590 Phase 2)
/// Replaces `record_test_verdict_remote`'s hand-built `json!` body
/// (#200/#590, settings_ui.rs). The `smoke_test` / `smoke_test_reason`
/// mirror is NOT derived here — deriving it is a client-side policy
/// decision (`coord test --pass/--fail` does the same derivation on the
/// Python side so `coord fix`'s `smoke_test == "fail"` guard sees it),
/// and this file only describes the wire.
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct TestVerdictRequest {
    pub(crate) assignment_id: String,
    pub(crate) test_state: String,
    pub(crate) test_reason: Option<String>,
    pub(crate) smoke_test: Option<String>,
    pub(crate) smoke_test_reason: Option<String>,
}

#[allow(dead_code)]
impl TestVerdictRequest {
    /// The route template, exactly as the daemon declares it.
    pub(crate) const PATH: &'static str = "/test-verdict";
    /// HTTP method for this route.
    pub(crate) const METHOD: &'static str = "POST";
    /// #1943: a verb route — send NO `X-Coord-Schema` header. Its
    /// absence means "today's shape", which is what keeps an
    /// un-migrated call working unchanged (docs/STORE_SERVICE.md §4).
    pub(crate) const SCHEMA_HEADER: Option<u32> = None;
    /// The concrete request path (no parameters).
    pub(crate) fn path() -> &'static str {
        Self::PATH
    }
}

/// `200` body of `POST /test-verdict`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
#[allow(dead_code)]
pub(crate) struct TestVerdictResponse {
    #[serde(default)]
    pub(crate) ok: Option<bool>,
}

/// `POST /issue-label` — Add/remove arbitrary labels on an issue through the tracker seam
/// (#802) [DEPRECATED #1944 — use PATCH /issue/{repo_name}/{number} (add_labels /
/// remove_labels); still fully supported, retirement is #1947]
/// Replaces `apply_issue_labels_remote`'s hand-built `json!` body (#1012).
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct IssueLabelRequest {
    pub(crate) repo_name: String,
    pub(crate) issue_number: i64,
    pub(crate) add: Option<Vec<String>>,
    pub(crate) remove: Option<Vec<String>>,
    pub(crate) repo_github: Option<String>,
}

#[allow(dead_code)]
impl IssueLabelRequest {
    /// The route template, exactly as the daemon declares it.
    pub(crate) const PATH: &'static str = "/issue-label";
    /// HTTP method for this route.
    pub(crate) const METHOD: &'static str = "POST";
    /// #1943: a verb route — send NO `X-Coord-Schema` header. Its
    /// absence means "today's shape", which is what keeps an
    /// un-migrated call working unchanged (docs/STORE_SERVICE.md §4).
    pub(crate) const SCHEMA_HEADER: Option<u32> = None;
    /// The concrete request path (no parameters).
    pub(crate) fn path() -> &'static str {
        Self::PATH
    }
}

/// `200` body of `POST /issue-label`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
#[allow(dead_code)]
pub(crate) struct IssueLabelResponse {
    #[serde(default)]
    pub(crate) labels: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) changed: Option<bool>,
}

/// `PATCH /issue/{repo_name}/{number}` — #1944: partial update of one issue — the
/// resource-shaped stand-in for POST /issue-edit, /issue-label, /issue-labels,
/// /issue-milestone, /issue-milestone-remove, /issue-close and /issue-reopen. Mutations
/// apply in a fixed order (content → labels → milestone → state). An explicit null
/// milestone clears it; an omitted key leaves it alone.
/// #1944's resource-shaped successor to `/issue-label` (and six other
/// RPC routes). Send `X-Coord-Schema` with this one — see
/// `SCHEMA_HEADER` below.
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct IssuePatchRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) title: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) body: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) add_labels: Option<Option<Vec<String>>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) remove_labels: Option<Option<Vec<String>>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) labels: Option<Option<Vec<String>>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) milestone: Option<Option<i64>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) milestone_title: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) state: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) comment: Option<Option<String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) force: Option<Option<bool>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub(crate) repo_github: Option<Option<String>>,
}

#[allow(dead_code)]
impl IssuePatchRequest {
    /// The route template, exactly as the daemon declares it.
    pub(crate) const PATH: &'static str = "/issue/{repo_name}/{number}";
    /// HTTP method for this route.
    pub(crate) const METHOD: &'static str = "PATCH";
    /// #1943: a resource-shaped route, so send `X-Coord-Schema: <this>`.
    pub(crate) const SCHEMA_HEADER: Option<u32> = Some(1);
    /// The concrete request path, with parameters interpolated.
    pub(crate) fn path(repo_name: &str, number: u64) -> String {
        format!("/issue/{repo_name}/{number}")
    }
}

/// `200` body of `PATCH /issue/{repo_name}/{number}`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
#[allow(dead_code)]
pub(crate) struct IssuePatchResponse {
    #[serde(default)]
    pub(crate) updated: bool,
    #[serde(default)]
    pub(crate) applied: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) labels: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) labels_changed: Option<bool>,
}

/// `POST /issue-upsert` — Upsert ONE issue row into the shared issue cache (#2895)
/// Replaces `upsert_issue_remote`'s hand-built `json!` body (#2895).
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct IssueUpsertRequest {
    pub(crate) repo_name: String,
    pub(crate) issue: IssueUpsertIssue,
}

#[allow(dead_code)]
impl IssueUpsertRequest {
    /// The route template, exactly as the daemon declares it.
    pub(crate) const PATH: &'static str = "/issue-upsert";
    /// HTTP method for this route.
    pub(crate) const METHOD: &'static str = "POST";
    /// #1943: a verb route — send NO `X-Coord-Schema` header. Its
    /// absence means "today's shape", which is what keeps an
    /// un-migrated call working unchanged (docs/STORE_SERVICE.md §4).
    pub(crate) const SCHEMA_HEADER: Option<u32> = None;
    /// The concrete request path (no parameters).
    pub(crate) fn path() -> &'static str {
        Self::PATH
    }
}

/// `200` body of `POST /issue-upsert`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
#[allow(dead_code)]
pub(crate) struct IssueUpsertResponse {
    #[serde(default)]
    pub(crate) ok: Option<bool>,
}

/// `POST /purge` — Count (dry_run) or delete old done/failed assignments and old closed
/// issues (#2895)
/// Replaces `purge_request`'s hand-built `json!` body (#2895) — and its
/// `resp.get(key).and_then(as_u64).unwrap_or(0)` response digging, which
/// is what `PurgeResponse` is for.
#[derive(Clone, Debug, Default, serde::Serialize)]
#[allow(dead_code)]
pub(crate) struct PurgeRequest {
    pub(crate) older_than_secs: f64,
    pub(crate) dry_run: Option<bool>,
}

#[allow(dead_code)]
impl PurgeRequest {
    /// The route template, exactly as the daemon declares it.
    pub(crate) const PATH: &'static str = "/purge";
    /// HTTP method for this route.
    pub(crate) const METHOD: &'static str = "POST";
    /// #1943: a verb route — send NO `X-Coord-Schema` header. Its
    /// absence means "today's shape", which is what keeps an
    /// un-migrated call working unchanged (docs/STORE_SERVICE.md §4).
    pub(crate) const SCHEMA_HEADER: Option<u32> = None;
    /// The concrete request path (no parameters).
    pub(crate) fn path() -> &'static str {
        Self::PATH
    }
}

/// `200` body of `POST /purge`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
#[allow(dead_code)]
pub(crate) struct PurgeResponse {
    #[serde(default)]
    pub(crate) assignments: Option<i64>,
    #[serde(default)]
    pub(crate) issues: Option<i64>,
}
