//! AUTO-GENERATED — DO NOT EDIT BY HAND.
//!
//! Generated by `scripts/codegen.py --rust` from `coord.serve_app.openapi_spec()`'s
//! `/board` response schema — itself built from the explicit wire DTOs in
//! `coord/board_schema.py` (#1849) — #1941. Regenerate after any field change:
//!
//! ```text
//! COORD_TUI_SRC=<coord-tui checkout root> .venv/bin/python scripts/codegen.py --rust
//! ```
//!
//! (The fence is load-bearing, and `text` is the load-bearing part of *it*:
//! a 4-space-indented block in a doc comment is a Markdown code block, and
//! rustdoc compiles an unannotated code block as a Rust doctest — so writing
//! that command as an indented block, or in a bare ``` fence, breaks
//! `cargo test --doc` with `error: expected item, found `.``.)
//!
//! #2897: the destination is named explicitly (`--out PATH` / `$COORD_TUI_SRC`
//! — see this script's module docstring), the same shape #2009 gave the TS
//! half. `tests/test_generated_rust_fixture.py` proves the generator runs and
//! covers every schema; the byte-for-byte freshness check against *this file
//! as committed* is coord-tui's own CI job once it exists
//! (`docs/ADR_COORD_TUI_CI.md`) rather than a test in this repo.
//!
//! **Every field defaults.** `/board` is one JSON payload: a single type
//! mismatch on a single field fails the *entire* `BoardPayload` parse and
//! blanks every TUI panel — the #632/#546/#628 failure class this repo has
//! been bitten by three times. INTEGER-backed boolean columns
//! (`is_interactive`, `hold_after`, `no_acceptance`, `review_scoped`) stay
//! typed as an integer, or go through a coercing deserializer — never a
//! plain `bool` — for the same reason (`coord/board_schema.py`'s
//! `INTEGER_BACKED_BOOLEANS`, asserted int-typed by `tests/test_board_schema.py`).
//!
//! Field types for anything already consumed by the TUI are hand-pinned in
//! `RUST_FIELD_OVERRIDES` (`scripts/codegen.py`) to match this file's
//! pre-existing behaviour exactly; anything else is generated mechanically
//! from the schema and marked `#[allow(dead_code)]` until a consumer reads it.

use super::{TestPlanStep, de_bool_from_int_or_bool, deserialize_test_plan};


/// One `assignments` row as `/board` carries it — the wire shape of
/// `coord.board_schema.BoardAssignment` (#1849/#1941).
///
/// #1042: `pub`, not `pub(crate)` — it's a parameter/return type of the
/// `test-support`-feature-gated fixtures in `app::fixtures` (e.g.
/// `make_app_with_assignments(Vec<Assignment>)`), which must be at least as
/// visible as those `pub fn`s (E0446) to be reachable from an external
/// integration-test crate. Fields stay `pub(crate)`: nothing outside the
/// crate constructs one field-by-field, only via `app::fixtures` helpers or
/// `serde::Deserialize`.
#[derive(Clone, serde::Deserialize)]
pub struct Assignment {
    #[serde(rename = "assignment_id")]
    pub(crate) id: String,
    #[serde(rename = "machine_name")]
    pub(crate) machine: String,
    #[serde(rename = "repo_name")]
    pub(crate) repo: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) repo_github: Option<String>,
    pub(crate) issue_number: u64,
    pub(crate) issue_title: String,
    pub(crate) status: String,
    #[serde(rename = "type", default)]
    pub(crate) assignment_type: Option<String>,
    #[serde(default)]
    pub(crate) branch: Option<String>,
    /// URL to the pull request for this work assignment (populated when the
    /// worker pushes a branch and the coordinator records it).
    /// `None` when no PR URL is known.
    #[serde(default)]
    pub(crate) pr_url: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) files_allowed: Option<Vec<String>>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) files_forbidden: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) model: Option<String>,
    #[serde(default)]
    pub(crate) dispatched_at: Option<f64>,
    #[serde(default)]
    pub(crate) finished_at: Option<f64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) smoke_test: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) smoke_test_reason: Option<String>,
    /// Internal review-state machine value: "pending" | "done" etc.
    /// `None` for non-review assignments and for pre-#876 rows.
    /// Deserialized from the board for future display; not yet read in
    /// production rendering paths.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_state: Option<String>,
    /// #253: links a review assignment back to the work assignment it
    /// reviews — needed to pair review_verdict with the merge entry.
    #[serde(default)]
    pub(crate) review_of_assignment_id: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_target: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) required_gates: Option<Vec<String>>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) plan: Option<serde_json::Value>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) unreachable_count: Option<i64>,
    #[serde(default)]
    pub(crate) exit_code: Option<i32>,
    /// #803: fix-round counter — 0 on the original work assignment, N on the
    /// N-th fix.  Used to compute the next iteration's escalated model via
    /// [`fix_model_for_iteration`]: `next_iteration = review_iteration + 1`.
    #[serde(default)]
    pub(crate) review_iteration: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_posted_at: Option<f64>,
    /// #200: human-driven Test gate verdict for type="work" assignments.
    /// None | "passed" | "failed" | "skipped".
    #[serde(default)]
    pub(crate) test_state: Option<String>,
    /// #876: test failure reason entered by the operator via `coord test --fail`
    /// (written by `record_test_verdict`).  `None` for assignments without a
    /// failed test or for pre-#876 rows.
    #[serde(default)]
    pub(crate) test_reason: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) uat_state: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) uat_reason: Option<String>,
    /// #208: worker cost captured from the final stream-json result event.
    /// `None` for in-flight workers and for pre-#208 rows.
    #[serde(default)]
    pub(crate) cost_usd: Option<f64>,
    /// #252: worker-emitted smoke-test list, parsed from the SMOKE_TESTS
    /// block in the worker's log.
    ///
    /// * `None`     — no block found (graceful degradation: TUI shows
    ///               "inspect the diff" placeholder).
    /// * `Some([])` — explicit "(none — change is internal)" form.
    /// * `Some(vec)` — bullets to render under the Test stage.
    ///
    /// #584: on the /board wire this is a real JSON array (already decoded),
    /// so plain serde handles it.
    #[serde(default)]
    pub(crate) smoke_tests: Option<Vec<String>>,
    /// #bounce: cached review findings (verdict + body), JSON-encoded
    /// in the DB column.  `None` for non-review assignments and for
    /// reviews completed before the cache landed.
    ///
    /// #584: intentionally kept as a raw JSON STRING on the /board wire, so
    /// plain serde deserialization works.
    #[serde(default)]
    pub(crate) review_findings: Option<String>,
    /// #349 Phase B: AI-generated smoke-test plan for type="work" assignments.
    /// Parsed from the JSON blob in `assignments.test_plan`.  `None` = not
    /// yet generated (TUI will spawn `coord test-plan` to fill it in).
    ///
    /// #584: on the /board wire this is a decoded OBJECT `{"steps":[...]}`,
    /// not an array — see [`deserialize_test_plan`].
    #[serde(default, deserialize_with = "deserialize_test_plan")]
    pub(crate) test_plan: Option<Vec<TestPlanStep>>,
    /// #253: parsed adversarial-review verdict for type="review" assignments.
    /// None | "approve" | "request-changes".  Drives the merge-gate hint
    /// swap so the user sees the block before pressing m.
    #[serde(default)]
    pub(crate) review_verdict: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) claude_session_id: Option<String>,
    /// #349 Phase B: git branch HEAD SHA at the time the cached test_plan was
    /// generated.  `None` when no plan exists or when it was generated without
    /// branch tracking.  Used to detect staleness (branch advanced →
    /// auto-refresh via `coord test-plan --refresh`).
    #[serde(default)]
    pub(crate) test_plan_branch_head: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) provider_name: Option<String>,
    /// #546: token counts for automated (claude -p) assignments, parsed from
    /// the final stream-json result event alongside `cost_usd`.
    /// 0 for interactive (Claude Max / OAuth) sessions — those have no
    /// per-token billing and the TUI shows "Max" instead of a $ figure.
    #[serde(default)]
    pub(crate) input_tokens: i64,
    #[serde(default)]
    pub(crate) output_tokens: i64,
    /// populated from DB / SSE; not yet read in TUI render (#818 removed the Stages tab that displayed them)
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) cache_creation_tokens: i64,
    /// see `cache_creation_tokens` above
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) cache_read_tokens: i64,
    /// #546: true when the assignment ran as a human-attended interactive session
    /// (Max / Pro subscription).  Set by `finalize_interactive_exit`; prevents
    /// misidentifying old automated rows (which also have cost_usd=NULL and zero
    /// token counts) as Max sessions.
    ///
    /// #628 hotfix: the daemon serializes this SQLite boolean as an int (0/1), so
    /// a strict `bool` here fails the ENTIRE /board parse on `is_interactive:0`,
    /// returning BoardData::default() and blanking every panel. Accept int-or-bool.
    #[serde(default, deserialize_with = "de_bool_from_int_or_bool")]
    pub(crate) is_interactive: bool,
    /// #618: short human-readable reason written immediately when an interactive
    /// session fails to launch (e.g. "branch already checked out at <path>").
    /// `None` for assignments that launched successfully.  Shown in the
    /// assignment detail panel so the TUI explains the red box without a log file.
    #[serde(default)]
    pub(crate) failure_reason: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_head_sha: Option<String>,
    /// #932/#944: the Acceptance-gate verdict (oracle loop,
    /// docs/ORACLE_LOOP.md) for type="work" assignments, stamped by `coord
    /// acceptance record --issue N --sha <sha>` — the coordinator's
    /// external re-run of the sealed suite against the pushed SHA.
    /// None | "passed" | "failed". Reported and gated SEPARATELY from
    /// `test_state` — its own box, its own verdict.
    #[serde(default)]
    pub(crate) acceptance_state: Option<String>,
    /// Short failing-test summary when `acceptance_state == "failed"`.
    #[serde(default)]
    pub(crate) acceptance_reason: Option<String>,
    /// SHA the last `acceptance record` verdict was recorded against.
    #[serde(default)]
    pub(crate) acceptance_sha: Option<String>,
    /// #932: per-test counts from the same verdict, so the Acceptance box
    /// can read as partial progress ("3/7 acceptance green") rather than a
    /// bare pass/fail — a growing suite is expected to be sub-100% until
    /// the feature completes. `None` for rows predating this column.
    #[serde(default)]
    pub(crate) acceptance_total: Option<i64>,
    #[serde(default)]
    pub(crate) acceptance_passed: Option<i64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) completion_summary: Option<String>,
    /// #886 Phase 2: Milestone Outcome Audit structured verdict, set only on
    /// `type="audit"` assignments (see #885's `--audit-of`). Kept as a raw
    /// JSON STRING on the wire, same convention as `review_findings` above.
    /// The Plans panel renders the *aggregated* latest-run-per-milestone view
    /// via `PlanRosterEntry`'s `outcome_*` fields, not this raw column — these
    /// are present for a possible future per-assignment audit detail view.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) audit_goals_json: Option<String>,
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) audit_bottom_line: Option<String>,
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) audit_run_number: Option<i64>,
    /// #1084: for `type="test-author"` JIT-mode assignments, the specific
    /// work-order member issue this dispatch is extending the acceptance
    /// suite for (`coord.test_author.dispatch_test_author`'s `issue_number`
    /// argument) — NOT the same as `issue_number` above, which test-author
    /// always sets to the milestone's *tracking* issue (every JIT dispatch
    /// for a milestone shares one branch/PR). `None` for milestone-mode
    /// (Gate A) authoring, every other assignment type, and rows predating
    /// this column. Used by the per-issue Acceptance-Authoring mini-
    /// pipeline to attribute a shared-branch assignment row back to the
    /// right member issue's row.
    #[serde(default)]
    pub(crate) for_issue_number: Option<u64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_verdict_original: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_verdict_override_reason: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_patch_id: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) test_head_sha: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) test_patch_id: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) test_base_sha: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_scoped: Option<i64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) review_scope_base_sha: Option<String>,
    /// #1499: durable provenance — `Some("drive:<repo>#<issue>")` when this
    /// assignment was dispatched by `coord drive` (via `coord assign
    /// --driven-by`), `None` for a hand `coord assign` and for rows
    /// predating this column. This is what lets the Pipeline distinguish a
    /// drive-dispatched row from a hand dispatch (and, combined with
    /// `drive_sessions`, "drive exited unfinished" from "never driven")
    /// even after the driver's tmux session is long gone — see
    /// `CoordApp::issue_has_drive_provenance` in `drive.rs`.
    #[serde(default)]
    pub(crate) driven_by: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) test_toolchain: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) verdict_source: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) verdict_source_reason: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) stop_reason: Option<String>,
    /// #2417: the CALLING assignment's id when this row was dispatched by a
    /// `coord` subcommand run from INSIDE another worker's own turn (e.g. a
    /// `type="work"` session shelling out to `coord acceptance author repo
    /// ms --issue N` or `coord fix <other-id>`), as opposed to a human
    /// typing the same command in their own shell. `None` for a hand or
    /// coordinator/brain dispatch, and for rows predating this column.
    /// Mirrors `coord.models.Assignment.dispatched_by_assignment_id`. Read
    /// in reverse via [`crate::app::CoordApp::dispatched_children`]: given
    /// an ORIGIN row, find every assignment whose value here equals the
    /// origin's `id` — that reverse lookup is what lets the origin row show
    /// "→ dispatched test-author <id> — running/done" instead of the
    /// operator having to grep the raw worker transcript (#2417).
    #[serde(default)]
    pub(crate) dispatched_by_assignment_id: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) num_turns: Option<i64>,
    /// #1337: true when the daemon bounded `review_findings` on the /board
    /// wire (the collection carries a preview; the full body lives on
    /// `GET /assignment/{id}`).  Absent (→ false) on pre-#1337 daemons and
    /// on the local-SQLite path, both of which carry the full text.
    ///
    /// Not part of `coord.board_schema.BoardAssignment` — stamped onto the row
    /// afterward by `coord/board_wire.py`'s per-field wire-bounding policy, so
    /// it can't be picked up by the schema-driven codegen above; kept here by
    /// hand alongside its `_len` sibling.
    #[serde(default)]
    pub(crate) review_findings_truncated: bool,
    /// #1337: full stored length of `review_findings` when truncated —
    /// combined with the assignment id as the detail-fetch cache key, so a
    /// force-overwritten review (different length) re-fetches.
    #[serde(default)]
    pub(crate) review_findings_len: Option<i64>,
}

/// #584: a machine row as it arrives on the `coord serve` /board wire.
///
/// `Machine` itself carries probe-only fields (reachable / active_count /
/// version / worktree_bytes) that never appear in the payload, so we
/// deserialize into this minimal shape and let `assemble_board_data` run the
/// reachability + health probes exactly like the SQLite path does.
#[derive(serde::Deserialize)]
pub(crate) struct RawMachine {
    pub(crate) name: String,
    pub(crate) host: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) capabilities: Option<Vec<String>>,
    #[serde(default)]
    pub(crate) repos: Vec<String>,
}

#[allow(dead_code)] // pr_url stored for future display
#[derive(Clone, serde::Deserialize)]
pub(crate) struct MergeQueueEntry {
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) id: Option<i64>,
    pub(crate) assignment_id: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) repo_name: String,
    /// Repo slug (owner/name) — keys the board-synced CI summary lookup in
    /// `pipeline_ci_checks` (see [`PlannedMergeEntry::ci_summary`]).
    /// Joined from the `merge_queue.repo_github` column.
    pub(crate) repo_github: String,
    /// Worker branch name — joined from `assignments.branch`.  Used by
    /// `compute_staging_local` for branch-level dedup (#778): a fix worker
    /// that shares a branch with an already-queued original work assignment
    /// must be excluded from staging even though it has a different assignment_id.
    #[serde(default)]
    pub(crate) branch: Option<String>,
    /// Target branch the PR merges into (e.g. "main").  `None` for entries
    /// written before this column was read by the TUI.
    #[serde(default)]
    pub(crate) target_branch: Option<String>,
    #[serde(default)]
    pub(crate) issue_number: Option<u64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) issue_title: String,
    pub(crate) state: String,
    #[serde(default)]
    pub(crate) pr_number: Option<i64>,
    #[serde(default)]
    pub(crate) pr_url: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) size: Option<i64>,
    /// Unix timestamp of the last merge attempt (`coord/merge_queue.py` sets
    /// this immediately before calling `gh pr merge`, and leaves it untouched
    /// on success) — for a `state == "merged"` entry this IS the merge time.
    /// #913: the Pipeline Done section's recency window + sort use this (via
    /// `issue_done_at`) instead of the work assignment's `finished_at`, so a
    /// freshly-merged item lands in Done immediately rather than being keyed
    /// off however long ago the work itself finished.
    #[serde(default)]
    pub(crate) last_attempt: Option<f64>,
    /// Last gate-eval error string from `coord merge`, if any.  Non-empty
    /// is the single most useful clue when a merge is stalled.
    #[serde(default)]
    pub(crate) error: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) enqueued_at: Option<f64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) assignment_type: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) required_gates: Option<Vec<String>>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_infra_reruns: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_stale_reruns: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_flaky_reruns: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_flaky_pending: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_unreadable_reruns: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) ci_fix_dispatches: i64,
    /// Milestone title — client-side join from `open_issues` keyed on
    /// `(repo_name, issue_number)`.  `None` when the issue carries no
    /// milestone or the issue row is absent from `open_issues`.
    ///
    /// Not part of `coord.board_schema.BoardMergeQueueEntry` — populated by a
    /// client-side join, not the wire itself; kept here by hand.
    #[serde(default)]
    pub(crate) milestone_title: Option<String>,
}

#[derive(Clone, serde::Deserialize)]
pub(crate) struct Proposal {
    pub(crate) id: i64,
    #[serde(rename = "machine_name")]
    pub(crate) machine: String,
    #[serde(rename = "repo_name")]
    pub(crate) repo: String,
    pub(crate) issue_number: u64,
    pub(crate) issue_title: String,
    pub(crate) rationale: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) files_likely: Option<Vec<String>>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) briefing: Option<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) model: Option<String>,
    #[serde(rename = "type")]
    pub(crate) proposal_type: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) required_gates: Option<Vec<String>>,
}

/// An open issue from the local `issues` table (synced from GitHub on coord plan).
#[derive(Clone, serde::Deserialize)]
pub(crate) struct OpenIssue {
    pub(crate) repo_name: String,
    pub(crate) number: u64,
    pub(crate) title: String,
    /// Issue body, synced from GitHub via `coord sync`.  Empty string when
    /// the issue has no description.
    #[serde(default)]
    pub(crate) body: String,
    /// "open" | "closed".  We load both into `data.open_issues` so the Board
    /// Issue tab can display bodies for closed issues (e.g. in the Completed
    /// group), but only "open" entries get injected as Pending rows.
    pub(crate) state: String,
    /// GitHub labels on this issue. Used by the Board Issue tab to render the
    /// same context the Pipeline Issue tab shows.
    #[serde(default)]
    pub(crate) labels: Vec<String>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) synced_at: Option<f64>,
    /// #406: GitHub milestone number.  `None` for issues without a milestone.
    #[serde(default)]
    pub(crate) milestone_number: Option<i64>,
    /// #406: GitHub milestone title (e.g. "v0.5").  `None` when no milestone.
    #[serde(default)]
    pub(crate) milestone_title: Option<String>,
    /// #2497: true when the `/board` wire bounded `body`. Set for every
    /// NON-EPIC issue, closed or open: `board_wire.bound_issue_row` drops a
    /// closed body to 0 chars (#1791) and an open one to its machine-parsed
    /// `**Allowed:**` residue (#1939), because the Issue tabs hydrate the
    /// real text lazily from `GET /issue/{repo}/{number}`. Absent only for
    /// epic bodies, which stay inline for the client-side Milestone DAG
    /// parse. `#[serde(default)]` so an older daemon (pre-#2497, never
    /// stamps this) deserializes as `false` — the pre-existing behavior of
    /// trusting `body` verbatim.
    ///
    /// Not part of `coord.board_schema.BoardIssue` — stamped onto the row
    /// afterward by `coord/board_wire.py`; kept here by hand alongside its
    /// `_len` sibling, same posture as `Assignment::review_findings_truncated`.
    #[serde(default)]
    pub(crate) body_truncated: bool,
    /// #2497: the issue's full body length before truncation. `Some` only
    /// when `body_truncated` is true; drives the Issue tab's hydration gate
    /// (`CoordApp::issue_body_fetch_target`).
    #[serde(default)]
    pub(crate) body_len: Option<i64>,
}

/// #1505: one board-visible "driver stuck" record — `coord drive`'s merge
/// stage hit a status no amount of retrying can fix (NEEDS_ATTENTION / an
/// unrecognised status) and escalated instead of burning the merge-attempt
/// budget on it. A raw dump of the `drive_escalations` table row, one
/// (repo_name, issue_number) at a time — see `coord/db.py`'s table comment
/// and `coord.drive._escalate_merge`.
#[derive(Clone, Debug, Default, serde::Deserialize)]
pub(crate) struct EscalationEntry {
    #[allow(dead_code)]
    pub(crate) id: i64,
    pub(crate) repo_name: String,
    pub(crate) issue_number: i64,
    /// #2427: which stage box on the Overview strip gets the "blocked" mark
    /// — see `CoordApp::build_pipeline_widget`'s `esc.stage == name` check.
    #[serde(default)]
    pub(crate) stage: String,
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) assignment_id: Option<String>,
    pub(crate) reason: String,
    /// Human-readable "key=value | key=value" summary of the gate readings
    /// the driver observed — deliberately NOT JSON (see `coord/db.py`): this
    /// record exists to be read by a human, not machine-parsed.
    ///
    /// Not yet surfaced in the TUI (unlike `stage`, #2427).
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) gate_readings: String,
    pub(crate) proposed_command: String,
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) created_at: Option<f64>,
}

/// #1753 (DQ-1) / #1755 (DQ-3): one row of the operator-declared `coord
/// drive` work queue — the wire shape of `/board`'s `drive_queue` array
/// (`coord.board_schema.BoardDriveQueueEntry`, a raw `drive_queue` table dump
/// via `coord.dao.SqliteStore.board_projection`; see `coord/db.py`'s table
/// comment for the storage contract).
///
/// **Every field is `#[serde(default)]` on purpose.** `/board` is one
/// payload: a single type mismatch on a single field fails the *entire*
/// `BoardPayload` parse and blanks every panel with no error message — the
/// #632/#546/#628 class this repo has been bitten by three times.
/// `tests.rs`'s `board_payload_deserializes_real_sample` round-trips the
/// golden fixture (which now carries a populated `drive_queue`) so schema
/// drift fails a test instead.
#[derive(Clone, Debug, Default, serde::Deserialize)]
pub(crate) struct BoardDriveQueueEntry {
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) id: Option<i64>,
    #[serde(default)]
    pub(crate) repo_name: String,
    #[serde(default)]
    pub(crate) issue_number: i64,
    /// Dense, 0-based run order (`coord/db.py`: no fractional positions —
    /// `move` renumbers the affected span in one transaction).
    #[serde(default)]
    pub(crate) position: i64,
    /// `None`/absent means "let `coord drive` route it" — NOT "unpinned is
    /// an error".
    #[serde(default)]
    pub(crate) machine: Option<String>,
    /// Pre-req keys (`"repo#N"`) that must land before this entry may start.
    ///
    /// Named `after` here but renamed from the wire's `after_json`: the
    /// column is a JSON *string* in SQLite and `coord.dao._JSON_COLUMNS`
    /// decodes it to a real array on the way out, keeping the column name.
    /// A plain `after` field would silently stay empty forever.
    #[serde(rename = "after_json", default)]
    pub(crate) after: Vec<String>,
    /// `waiting` | `running` | `blocked` | `done` | … — decided by DQ-2's
    /// tick, never re-derived here (same posture as `fleet_health.rs`'s
    /// "renderers consume `severity` verbatim").
    #[serde(default)]
    pub(crate) state: String,
    #[serde(default)]
    pub(crate) attempts: i64,
    /// How many ticks skipped this entry because it wasn't eligible yet.
    /// Surfaced in the overlay next to `last_reason` — a row that keeps
    /// being passed over is the thing an operator most needs to see.
    #[serde(default)]
    pub(crate) deferrals: i64,
    #[serde(default)]
    pub(crate) last_reason: String,
    /// #2133: capture time of `last_reason` — `last_reason` is a
    /// point-in-time observation, never re-validated, so the Queue panel
    /// age-stamps it (`queue_row`) rather than rendering it bare as if it
    /// were current state. `None` for a row predating the migration or one
    /// whose `last_reason` is still the `""` default.
    #[serde(default)]
    pub(crate) reason_at: Option<f64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) session_name: Option<String>,
    /// wire parity; the Queue panel shows `state`, not the clock
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) launched_at: Option<f64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) enqueued_at: f64,
    /// #1757: this entry ends with a DEPLOY GATE — when it completes, the
    /// tick launches nothing until a human deploys and releases it.
    ///
    /// SQLite stores 0/1 in an `INTEGER` column, so this is `i64`, not
    /// `bool`: an `INTEGER` column deserialised into a Rust `bool` is the
    /// exact #632/#546/#628 type mismatch that blanks the whole board (see
    /// `tests/test_board_fixture.py::
    /// test_no_unguarded_integer_bool_columns_reach_the_wire`).
    #[serde(default)]
    pub(crate) hold_after: i64,
    /// What the operator must do while the gate is held — rendered verbatim.
    #[serde(default)]
    pub(crate) hold_reason: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) resume_when: String,
    /// `""` | `armed` | `fired` | `released` — decided by the tick, consumed
    /// verbatim here (same posture as `state` above).
    #[serde(default)]
    pub(crate) hold_state: String,
    /// Consecutive failed `resume_when` runs since the gate fired. A rising
    /// count is how a gate that never clears becomes visible instead of
    /// silent, so it is carried on the wire rather than re-derived.
    #[serde(default)]
    pub(crate) hold_probes: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) launch_host: String,
    /// #2186: how FAR a fired gate reaches — `"entry"` (the default) holds
    /// only entries whose own `after` names this gate's key; `"fleet"` is
    /// the pre-#2186 whole-queue stop, now opt-in only.
    ///
    /// Fail-closed, mirroring `coord.drive_queue.QueueEntry.
    /// _normalize_hold_scope`: `""` (a row predating this column, or any
    /// other server this build has never heard of) reads as entry-scoped,
    /// the narrower/safer reading — NEVER as fleet-wide. See
    /// `drive_queue::stops_fleet`, the one place this is consulted.
    #[serde(default)]
    pub(crate) hold_scope: String,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) resumes: i64,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) retry_backoff_at: Option<f64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) max_fix_rounds: Option<i64>,
    /// Wire field from `coord.board_schema` (#1941) — no TUI consumer yet.
    #[allow(dead_code)]
    #[serde(default)]
    pub(crate) no_acceptance: i64,
}
